In [1]:
# Step 1 — Import libraries

import pandas as pd
import numpy as np

In [3]:
# Step 2 — Load the raw dataset

import pandas as pd

orders = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Data_Cleaning\data\retail-orders-raw.csv")

orders.head()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03/01/2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid

In [4]:
# Step 3 — Check dataset size

print("Number of rows:", orders.shape[0])
print("Number of columns:", orders.shape[1])

Number of rows: 12
Number of columns: 9

In [5]:
orders.shape

(12, 9)

In [10]:
# Step 4: Inspect the raw dataset
orders.head(10)

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2,799,10.0,Paid
1,RT-1002,03/01/2026,Fresher,Bengaluru,Course Access,1,1499,0.0,paid
2,RT-1003,2026-01-05,student,Chennai,Course Access,1,1499,NaN,Pending
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid
5,RT-1005,2026-01-09,Fresher,NaN,Mentor Session,1,999,0.0,Failed
6,RT-1006,2026-13-10,Student,Pune,Learning Kit,-1,799,10.0,Paid
7,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
8,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
9,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid

In [11]:
orders.tail()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
7,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2,999,105.0,Paid
8,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,two,1499,0.0,Pending
9,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1,799,0.0,Paid
10,RT-1010,2026-01-18,Professional,Delhi,Course Access,2,1499,15.0,Refunded
11,RT-1011,NaN,Student,Kochi,Mentor Session,1,999,0.0,Paid

In [8]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          12 non-null     object
 1   order_date        11 non-null     object
 2   customer_segment  12 non-null     object
 3   city              11 non-null     object
 4   category          12 non-null     object
 5   quantity          12 non-null     object
 6   unit_price        12 non-null     int64
 7   discount_pct      11 non-null     float64
 8   payment_status    12 non-null     object
dtypes: float64(1), int64(1), object(7)
memory usage: 996.0+ bytes

In [9]:
orders.describe(include="all")

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
count,12,11,12,11,12,12,12.000000,11.000000,12
unique,11,10,4,7,3,5,NaN,NaN,5
top,RT-1004,2026-01-07,Student,Chennai,Learning Kit,1,NaN,NaN,Paid
freq,2,2,4,3,5,5,NaN,NaN,7
mean,NaN,NaN,NaN,NaN,NaN,NaN,1082.333333,13.636364,NaN
std,NaN,NaN,NaN,NaN,NaN,NaN,318.614425,30.748245,NaN
min,NaN,NaN,NaN,NaN,NaN,NaN,799.000000,0.000000,NaN
25%,NaN,NaN,NaN,NaN,NaN,NaN,799.000000,0.000000,NaN
50%,NaN,NaN,NaN,NaN,NaN,NaN,999.000000,5.000000,NaN
75%,NaN,NaN,NaN,NaN,NaN,NaN,1499.000000,10.000000,NaN
max,NaN,NaN,NaN,NaN,NaN,NaN,1499.000000,105.000000,NaN

In [12]:
# Step 5 — Check column names

orders.columns.tolist()

['order_id',
 'order_date',
 'customer_segment',
 'city',
 'category',
 'quantity',
 'unit_price',
 'discount_pct',
 'payment_status']

In [14]:
# Step 6 — Check missing values

missing_count = orders.isna().sum()

missing_count

order_id            0
order_date          1
customer_segment    0
city                1
category            0
quantity            0
unit_price          0
discount_pct        1
payment_status      0
dtype: int64

In [15]:
# calculate missing percentage

missing_percent = (
    orders.isna().sum() / len(orders) * 100
)

missing_percent

order_id            0.000000
order_date          8.333333
customer_segment    0.000000
city                8.333333
category            0.000000
quantity            0.000000
unit_price          0.000000
discount_pct        8.333333
payment_status      0.000000
dtype: float64

In [16]:
#Create a nice table:

missing_profile = pd.DataFrame({
    "Missing Count": orders.isna().sum(),
    "Missing %": orders.isna().sum() / len(orders) * 100
})

missing_profile

                  Missing Count  Missing %
order_id                      0   0.000000
order_date                    1   8.333333
customer_segment              0   0.000000
city                          1   8.333333
category                      0   0.000000
quantity                      0   0.000000
unit_price                    0   0.000000
discount_pct                  1   8.333333
payment_status                0   0.000000

In [17]:
# Step 7 — Check duplicate records

duplicate_count = orders.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 1

In [18]:
#Calculate Percentage

duplicate_percent = (
    duplicate_count / len(orders) * 100
)

print("Duplicate percentage:", duplicate_percent)

Duplicate percentage: 8.333333333333332

In [19]:
# View duplicates:

orders[orders.duplicated()].head()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status
4,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3,799,5.0,Paid

In [20]:
# Step 8 — Check data types

orders.dtypes

order_id             object
order_date           object
customer_segment     object
city                 object
category             object
quantity             object
unit_price            int64
discount_pct        float64
payment_status       object
dtype: object

In [22]:
# Step 9 — Check unique values
    # For categorical columns

print(orders["customer_segment"].unique())

['Student' 'Fresher' 'student' 'Professional']

In [23]:
print(orders["city"].unique())

['Chennai' 'Bengaluru' 'Hyderabad' nan 'Pune' 'Mumbai' 'Delhi' 'Kochi']

In [24]:
print(orders["category"].unique())

['Learning Kit' 'Course Access' 'Mentor Session']

In [25]:
print(orders["payment_status"].unique())

['Paid' 'paid' 'Pending' 'Failed' 'Refunded']

In [28]:
# Step 10 — Convert date column

orders["order_date"].dtype

dtype('<M8[ns]')

In [29]:
# Convert

orders["order_date"] = pd.to_datetime(
    orders["order_date"],
    errors="coerce"
)

In [30]:
# Check

orders["order_date"].dtype

dtype('<M8[ns]')

In [31]:
# Step 11 — Convert numeric columns

orders["quantity"] = pd.to_numeric(
    orders["quantity"],
    errors="coerce"
)

orders["unit_price"] = pd.to_numeric(
    orders["unit_price"],
    errors="coerce"
)

orders["discount_pct"] = pd.to_numeric(
    orders["discount_pct"],
    errors="coerce"
)

In [32]:
orders.dtypes

order_id                    object
order_date          datetime64[ns]
customer_segment            object
city                        object
category                    object
quantity                   float64
unit_price                   int64
discount_pct               float64
payment_status              object
dtype: object

In [33]:
# Step 12 — Standardize text columns

text_columns = [
    "customer_segment",
    "city",
    "category",
    "payment_status"
]

for col in text_columns:
    orders[col] = orders[col].astype("string").str.strip()

In [34]:
# Step 13 — Standardize categorical values

orders["customer_segment"] = (
    orders["customer_segment"]
    .str.title()
)

In [35]:
# City
orders["city"] = orders["city"].str.title()

In [36]:
# Category

orders["category"] = orders["category"].str.title()

In [37]:
# Payment Status

orders["payment_status"] = (
    orders["payment_status"]
    .str.title()
)

In [38]:
orders["payment_status"].value_counts(dropna=False)

payment_status
Paid        8
Pending     2
Failed      1
Refunded    1
Name: count, dtype: Int64

In [39]:
# Step 14 — Handle missing values

orders.isna().sum()

order_id            0
order_date          3
customer_segment    0
city                1
category            0
quantity            1
unit_price          0
discount_pct        1
payment_status      0
dtype: int64

In [40]:
#Quantity

orders["quantity"] = orders["quantity"].fillna(
    orders["quantity"].median()
)

In [41]:
# Unit Price

orders["unit_price"] = orders["unit_price"].fillna(
    orders["unit_price"].median()
)

In [42]:
# Discount

orders["discount_pct"] = orders["discount_pct"].fillna(0)

In [43]:
# categorical values

orders["customer_segment"] = orders["customer_segment"].fillna(
    "Unknown"
)

orders["city"] = orders["city"].fillna(
    "Unknown"
)

orders["category"] = orders["category"].fillna(
    "Unknown"
)

orders["payment_status"] = orders["payment_status"].fillna(
    "Unknown"
)

In [44]:
# For Dates

orders["order_date"] = orders["order_date"].fillna(
    orders["order_date"].median()
)

In [45]:
# Step 15 — Check missing values after cleaning

orders.isna().sum()

order_id            0
order_date          0
customer_segment    0
city                0
category            0
quantity            0
unit_price          0
discount_pct        0
payment_status      0
dtype: int64

In [46]:
# Step 16 — Remove duplicate records

before_duplicates = len(orders)

orders = orders.drop_duplicates()

after_duplicates = len(orders)

print("Rows before:", before_duplicates)
print("Rows after:", after_duplicates)
print("Duplicates removed:", before_duplicates - after_duplicates)

Rows before: 12
Rows after: 11
Duplicates removed: 1

In [47]:
# Step 17 — Check outliers

orders[["quantity", "unit_price", "discount_pct"]].describe()

        quantity   unit_price  discount_pct
count  11.000000    11.000000     11.000000
mean    1.272727  1108.090909     13.181818
std     1.009050   320.794468     30.925130
min    -1.000000   799.000000      0.000000
25%     1.000000   799.000000      0.000000
50%     1.000000   999.000000      0.000000
75%     2.000000  1499.000000     10.000000
max     3.000000  1499.000000    105.000000

In [48]:
#Quantity outliers

#Calculate IQR:

Q1 = orders["quantity"].quantile(0.25)
Q3 = orders["quantity"].quantile(0.75)

IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

quantity_outliers = orders[
    (orders["quantity"] < lower_bound) |
    (orders["quantity"] > upper_bound)
]

print("Quantity outliers:", len(quantity_outliers))

Quantity outliers: 1

In [49]:
# Step 18 — Handle unrealistic values

#Quantity
#Quantity should not be negative

(orders["quantity"] < 0).sum()

1

In [50]:
orders = orders[orders["quantity"] >= 0]

In [51]:
# Unit Price
(orders["unit_price"] < 0).sum()

0

In [52]:
# Remove invalid negative prices:
orders = orders[orders["unit_price"] >= 0]

In [53]:
# Discount

invalid_discount = (
    (orders["discount_pct"] < 0) |
    (orders["discount_pct"] > 100)
)

invalid_discount.sum()

1

In [54]:
# Handled them

orders.loc[
    orders["discount_pct"] < 0,
    "discount_pct"
] = 0

orders.loc[
    orders["discount_pct"] > 100,
    "discount_pct"
] = 100

# Step 19 — Feature Engineering

This is specifically required for our  assignment.

We will create:

Year
Month
Month Name
Gross Sales
Discount Amount
Net Sales

In [55]:
# Extract year

orders["year"] = orders["order_date"].dt.year

In [56]:
# Extract month

orders["month"] = orders["order_date"].dt.month

In [57]:
# Extract month name

orders["month_name"] = (
    orders["order_date"].dt.month_name()
)

In [58]:
# Step 20 — Calculate Gross Sales

#Formula -->(Gross Sales = Quantity × Unit Price)

orders["gross_sales"] = (
    orders["quantity"] *
    orders["unit_price"]
)

In [59]:
# Step 21 — Calculate Discount Amount

# Formula -->(Discount Amount = Gross Sales × Discount % / 100)

orders["discount_amount"] = (
    orders["gross_sales"] *
    orders["discount_pct"] / 100
)

In [60]:
# Step 22 — Calculate Net Sales

#Formula --> (Net Sales = Gross Sales - Discount Amount)

orders["net_sales"] = (
    orders["gross_sales"] -
    orders["discount_amount"]
)

In [61]:
orders[
    [
        "quantity",
        "unit_price",
        "discount_pct",
        "gross_sales",
        "discount_amount",
        "net_sales"
    ]
].head()

   quantity  unit_price  discount_pct  gross_sales  discount_amount  net_sales
0       2.0         799          10.0       1598.0           159.80    1438.20
1       1.0        1499           0.0       1499.0             0.00    1499.00
2       1.0        1499           0.0       1499.0             0.00    1499.00
3       3.0         799           5.0       2397.0           119.85    2277.15
5       1.0         999           0.0        999.0             0.00     999.00

# Step 23 — Profit Margin

My  dataset doesn't contain cost price or profit, so I should not invent a profit margin.

Instead, document this limitation in my  notebook:

Profit margin cannot be calculated because the raw dataset does not contain
cost price, COGS, or profit information.

I can calculate discount rate and net sales, but not actual profit margin.

This is much better than creating fake profit numbers.

In [62]:
# Step 24 — Final data type check

orders.dtypes

order_id                    object
order_date          datetime64[ns]
customer_segment    string[python]
city                string[python]
category            string[python]
quantity                   float64
unit_price                   int64
discount_pct               float64
payment_status      string[python]
year                         int32
month                        int32
month_name                  object
gross_sales                float64
discount_amount            float64
net_sales                  float64
dtype: object

In [63]:
# Step 25 — Before/After comparison

before_rows = len(pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Data_Cleaning\data\retail-orders-raw.csv"))
after_rows = len(orders)

print("BEFORE CLEANING")
print("----------------")
print("Rows:", before_rows)

print("\nAFTER CLEANING")
print("----------------")
print("Rows:", after_rows)

print("\nRows removed:", before_rows - after_rows)

BEFORE CLEANING
----------------
Rows: 12

AFTER CLEANING
----------------
Rows: 10

Rows removed: 2

In [65]:
# Step 26 — Compare missing values

raw_data = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Data_Cleaning\data\retail-orders-raw.csv")

before_missing = raw_data.isna().sum()
after_missing = orders.isna().sum()

comparison = pd.DataFrame({
    "Before Missing": before_missing,
    "After Missing": after_missing
})

comparison

                  Before Missing  After Missing
category                     0.0              0
city                         1.0              0
customer_segment             0.0              0
discount_amount              NaN              0
discount_pct                 1.0              0
gross_sales                  NaN              0
month                        NaN              0
month_name                   NaN              0
net_sales                    NaN              0
order_date                   1.0              0
order_id                     0.0              0
payment_status               0.0              0
quantity                     0.0              0
unit_price                   0.0              0
year                         NaN              0

In [66]:
# Step 27 — Compare data types

dtype_comparison = pd.DataFrame({
    "Column": orders.columns,
    "Final Data Type": orders.dtypes.astype(str).values
})

dtype_comparison

              Column Final Data Type
0           order_id          object
1         order_date  datetime64[ns]
2   customer_segment          string
3               city          string
4           category          string
5           quantity         float64
6         unit_price           int64
7       discount_pct         float64
8     payment_status          string
9               year           int32
10             month           int32
11        month_name          object
12       gross_sales         float64
13   discount_amount         float64
14         net_sales         float64

In [67]:
# Step 28 — Final quality checks

print("Missing values:")
print(orders.isna().sum())

Missing values:
order_id            0
order_date          0
customer_segment    0
city                0
category            0
quantity            0
unit_price          0
discount_pct        0
payment_status      0
year                0
month               0
month_name          0
gross_sales         0
discount_amount     0
net_sales           0
dtype: int64

In [68]:
print("\nDuplicate rows:")
print(orders.duplicated().sum())

Duplicate rows:
0

In [69]:
print("\nDuplicate rows:")
print(orders.duplicated().sum())

Duplicate rows:
0

In [70]:
print("\nNegative unit prices:")
print((orders["unit_price"] < 0).sum())

Negative unit prices:
0

In [71]:
print("\nInvalid discounts:")
print(
    (
        (orders["discount_pct"] < 0) |
        (orders["discount_pct"] > 100)
    ).sum()
)

Invalid discounts:
0

In [72]:
# Step 29 — Inspect final dataset

orders.head()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status,year,month,month_name,gross_sales,discount_amount,net_sales
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2.0,799,10.0,Paid,2026,1,January,1598.0,159.80,1438.20
1,RT-1002,2026-01-09,Fresher,Bengaluru,Course Access,1.0,1499,0.0,Paid,2026,1,January,1499.0,0.00,1499.00
2,RT-1003,2026-01-05,Student,Chennai,Course Access,1.0,1499,0.0,Pending,2026,1,January,1499.0,0.00,1499.00
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3.0,799,5.0,Paid,2026,1,January,2397.0,119.85,2277.15
5,RT-1005,2026-01-09,Fresher,Unknown,Mentor Session,1.0,999,0.0,Failed,2026,1,January,999.0,0.00,999.00

In [73]:
orders.tail()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status,year,month,month_name,gross_sales,discount_amount,net_sales
7,RT-1007,2026-01-12,Professional,Mumbai,Mentor Session,2.0,999,100.0,Paid,2026,1,January,1998.0,1998.0,0.0
8,RT-1008,2026-01-14,Fresher,Bengaluru,Course Access,1.0,1499,0.0,Pending,2026,1,January,1499.0,0.0,1499.0
9,RT-1009,2026-01-16,Student,Chennai,Learning Kit,1.0,799,0.0,Paid,2026,1,January,799.0,0.0,799.0
10,RT-1010,2026-01-18,Professional,Delhi,Course Access,2.0,1499,15.0,Refunded,2026,1,January,2998.0,449.7,2548.3
11,RT-1011,2026-01-09,Student,Kochi,Mentor Session,1.0,999,0.0,Paid,2026,1,January,999.0,0.0,999.0

In [74]:
orders.info()

<class 'pandas.core.frame.DataFrame'>
Index: 10 entries, 0 to 11
Data columns (total 15 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_id          10 non-null     object
 1   order_date        10 non-null     datetime64[ns]
 2   customer_segment  10 non-null     string
 3   city              10 non-null     string
 4   category          10 non-null     string
 5   quantity          10 non-null     float64
 6   unit_price        10 non-null     int64
 7   discount_pct      10 non-null     float64
 8   payment_status    10 non-null     string
 9   year              10 non-null     int32
 10  month             10 non-null     int32
 11  month_name        10 non-null     object
 12  gross_sales       10 non-null     float64
 13  discount_amount   10 non-null     float64
 14  net_sales         10 non-null     float64
dtypes: datetime64[ns](1), float64(5), int32(2), int64(1), object(2), string(4)
memory usage: 1.2+ KB

In [75]:
# Step 30 — Export clean CSV

orders.to_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Data_Cleaning\output\clean_dataset.csv",index=False)

In [77]:
# Step 31 — Verify the exported file

clean_check = pd.read_csv(r"C:\Users\HP\OneDrive\Desktop\Retail_Data_Cleaning\output\clean_dataset.csv")
clean_check.head()

,order_id,order_date,customer_segment,city,category,quantity,unit_price,discount_pct,payment_status,year,month,month_name,gross_sales,discount_amount,net_sales
0,RT-1001,2026-01-03,Student,Chennai,Learning Kit,2.0,799,10.0,Paid,2026,1,January,1598.0,159.80,1438.20
1,RT-1002,2026-01-09,Fresher,Bengaluru,Course Access,1.0,1499,0.0,Paid,2026,1,January,1499.0,0.00,1499.00
2,RT-1003,2026-01-05,Student,Chennai,Course Access,1.0,1499,0.0,Pending,2026,1,January,1499.0,0.00,1499.00
3,RT-1004,2026-01-07,Professional,Hyderabad,Learning Kit,3.0,799,5.0,Paid,2026,1,January,2397.0,119.85,2277.15
4,RT-1005,2026-01-09,Fresher,Unknown,Mentor Session,1.0,999,0.0,Failed,2026,1,January,999.0,0.00,999.00

In [78]:
# shape
clean_check.shape

(10, 15)

In [79]:
# Missing Values

clean_check.isna().sum()

order_id            0
order_date          0
customer_segment    0
city                0
category            0
quantity            0
unit_price          0
discount_pct        0
payment_status      0
year                0
month               0
month_name          0
gross_sales         0
discount_amount     0
net_sales           0
dtype: int64

In [80]:
# Duplicate
clean_check.duplicated().sum()

0